#We have two configure for get backup vlan.
#1: this config has tested and result was successful

- name: ---- Show Vlan.dat configure ----
  ios_command:
      commands: "show vlan"
  register: vlanconfig

- name: ---- get timestamp ----
  command: date +%Y%m%d
  register: timestamp

- name: ---- copy Vlan.dat to backup directory ----
  copy:
      content: "{{ vlanconfig.stdout[0] }}"
      dest: "/home/infra/{{timestamp.stdout}}_vlan.dat"
      
#2: this one has not yet test
---
- name: backup configuration
  hosts: csr
  gather_facts: false
  connection: network_cli

  vars:
    backup_root: ./backups

    cli:
      host: "{{ inventory_hostname }}"
      username: rayka
      password: rayka-co.com
      authorize: true

  tasks:
    - name: run show running-config on remote devices
      ios_command:
        commands: "show running-config"
        provider: "{{ cli }}"
      register: config

    - name: ensure backup folder is created
      file:
        path: "{{ backup_root }}"
        state: directory
      run_once: yes

    - name: ensure device rolder is created
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}"
        state: directory

    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp

    - name: get/copy backup
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}"
