---
- name: Get date of windows server
  win_shell: |
     Get-Date -Format G
  register: date_output

- name: Show date and time
  debug:
    msg: "Current date is {{ date_output.stdout }}"

- name: SNMP service status
  win_shell: |
        $ServiceName = "SNMP"
        $ServiceStatus = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
        if ($ServiceStatus.Status -eq "Running") {Write-Host "The SNMP service is running."}
           else {Write-Host "The SNMP service is not running."}
  register: snmp_output

- name: Show SNMP status
  debug:
    msg: "Current status {{ snmp_output.stdout }}"

- name: SQL service status
  win_shell: |
        $ServiceName = "MSSQLSERVER"
        $ServiceStatus = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
        if ($ServiceStatus.Status -eq "Running") {Write-Host "The MSSQLSERVER service is running."}
           else {Write-Host "The SQL service is not running."}
  register: sql_output

- name: Show SQL status
  debug:
    msg: "Current status {{ sql_output.stdout }}"

- name: azure app pool status
  community.windows.win_iis_webapppool:
     name: AzureDevOpsServerApplicationPool
     state: present
#   register: pool_out

# - name: Show app pool status
#   debug:
#     msg: "AzureDevops App-pool Status {{ pool_out.stdout }}"